import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";

function writeJson(root,relative,value){const file=path.join(root,relative);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,`${JSON.stringify(value,null,2)}\n`)}
function copyRuntime(tmp,files){const scripts=path.join(tmp,"scripts");fs.mkdirSync(scripts,{recursive:true});for(const file of files)fs.copyFileSync(path.join("scripts",file),path.join(scripts,file))}
function setupBase(tmp,provider="chatgpt"){copyRuntime(tmp,[`finalize-${provider}.mjs`,"lib.mjs","status-contract.mjs"]);const status=JSON.parse(fs.readFileSync(`providers/${provider}/status.json`,"utf8")),signal=JSON.parse(fs.readFileSync(`providers/${provider}/signal.json`,"utf8")),history=JSON.parse(fs.readFileSync(`providers/${provider}/history.json`,"utf8")),latest=history.items.at(-1);assert.ok(latest);fs.mkdirSync(path.join(tmp,path.dirname(latest.snapshot)),{recursive:true});fs.copyFileSync(latest.snapshot,path.join(tmp,latest.snapshot));writeJson(tmp,`providers/${provider}/status.json`,status);writeJson(tmp,`providers/${provider}/signal.json`,signal);writeJson(tmp,`providers/${provider}/history.json`,{...history,items:[latest]});return{status,latest}}
function run(tmp,script,args=[]){return spawnSync(process.execPath,[`scripts/${script}`,...args],{cwd:tmp,encoding:"utf8"})}

test("invalid unindexed snapshot cannot poison a later valid snapshot",t=>{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),"tb-finalizer-"));t.after(()=>fs.rmSync(tmp,{recursive:true,force:true}));const{status}=setupBase(tmp);fs.mkdirSync(path.join(tmp,"providers/chatgpt/snapshots/2027/01"),{recursive:true});fs.writeFileSync(path.join(tmp,"providers/chatgpt/snapshots/2027/01/a-bad.json"),"{bad json\n");const next={...status,generatedAt:new Date(Date.parse(status.generatedAt)+1000).toISOString()};writeJson(tmp,"providers/chatgpt/snapshots/2027/01/z-good.json",next);const result=run(tmp,"finalize-chatgpt.mjs"),output=`${result.stdout}\n${result.stderr}`;assert.equal(result.status,0,output);assert.match(result.stderr,/Rejected 1 invalid unindexed ChatGPT snapshot/);const finalStatus=JSON.parse(fs.readFileSync(path.join(tmp,"providers/chatgpt/status.json"),"utf8"));assert.equal(finalStatus.generatedAt,next.generatedAt)});

test("invalid indexed snapshot remains a hard failure",t=>{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),"tb-finalizer-"));t.after(()=>fs.rmSync(tmp,{recursive:true,force:true}));const{latest}=setupBase(tmp),indexed=JSON.parse(fs.readFileSync(path.join(tmp,latest.snapshot),"utf8"));indexed.dominantMode="invalid";writeJson(tmp,latest.snapshot,indexed);const result=run(tmp,"finalize-chatgpt.mjs");assert.notEqual(result.status,0);assert.match(result.stderr,/is indexed but invalid/)});

test("Claude rejects invalid unindexed snapshots and finalizes a later valid snapshot",t=>{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),"tb-claude-finalizer-"));t.after(()=>fs.rmSync(tmp,{recursive:true,force:true}));const{status}=setupBase(tmp,"claude"),snapshotDir="providers/claude/snapshots/2027/01";fs.mkdirSync(path.join(tmp,snapshotDir),{recursive:true});fs.writeFileSync(path.join(tmp,snapshotDir,"a-bad-json.json"),"{bad json\n");const badContract=structuredClone(status),basicOffset=value=>value.replace(/([+-]\d{2}):(\d{2})$/,"$1$2");badContract.forecast[0].timeBerlin=basicOffset(badContract.forecast[0].timeBerlin);badContract.forecastDetail[0].timeBerlin=basicOffset(badContract.forecastDetail[0].timeBerlin);writeJson(tmp,`${snapshotDir}/b-bad-contract.json`,badContract);const next={...status,generatedAt:new Date(Date.parse(status.generatedAt)+1000).toISOString()};writeJson(tmp,`${snapshotDir}/z-good.json`,next);const result=run(tmp,"finalize-claude.mjs"),output=`${result.stdout}\n${result.stderr}`;assert.equal(result.status,0,output);assert.match(result.stderr,/Rejected 2 invalid unindexed Claude snapshot/);assert.match(result.stderr,/forecast\[0\]\.timeBerlin must represent the same instant with an explicit offset/);const finalStatus=JSON.parse(fs.readFileSync(path.join(tmp,"providers/claude/status.json"),"utf8")),history=JSON.parse(fs.readFileSync(path.join(tmp,"providers/claude/history.json"),"utf8"));assert.equal(finalStatus.generatedAt,next.generatedAt);assert.equal(history.items.at(-1).snapshot,`${snapshotDir}/z-good.json`)});

test("Claude invalid indexed snapshot remains a hard failure",t=>{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),"tb-claude-finalizer-"));t.after(()=>fs.rmSync(tmp,{recursive:true,force:true}));const{latest}=setupBase(tmp,"claude");fs.writeFileSync(path.join(tmp,latest.snapshot),"{bad json\n");const result=run(tmp,"finalize-claude.mjs");assert.notEqual(result.status,0);assert.match(result.stderr,/is indexed but contains invalid JSON/)});

test("provider with snapshots but missing all state files is not treated as first-run",t=>{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),"tb-provider-"));t.after(()=>fs.rmSync(tmp,{recursive:true,force:true}));copyRuntime(tmp,["validate-provider.mjs","lib.mjs","status-contract.mjs"]);fs.mkdirSync(path.join(tmp,"providers/example/snapshots/2026/01"),{recursive:true});fs.writeFileSync(path.join(tmp,"providers/example/snapshots/2026/01/x.json"),"{}\n");const result=run(tmp,"validate-provider.mjs",["example"]);assert.notEqual(result.status,0);assert.match(result.stderr,/was initialized before/)});

test("both provider finalizers apply the shared contract before indexing new snapshots",()=>{
  for(const file of["scripts/finalize-chatgpt.mjs","scripts/finalize-claude.mjs"]){
    const source=fs.readFileSync(file,"utf8");
    assert.match(source,/import \{ validateStatusContract \} from "\.\/status-contract\.mjs"/);
    assert.match(source,/if\s*\(!indexed\).*validateStatusContract/);
  }
});
